services:
  backend:
    build: backend
    container_name: starstream-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend-uploads:/uploads/
    expose:
      - 8000
  db:
    image: mysql
    container_name: starstream-db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=starstream_db
      - MYSQL_ROOT_PASSWORD=starstreampw
    ports:
      - 3306
  web:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./vuejs:/project
      - /project/node_modules
volumes:
  db-data:
  backend-uploads: